# Generated by Django 5.2.3 on 2025-06-25 09:51

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='default.png', upload_to=job.models.job_image_upload_to),
        ),
    ]
